### ISSUE TITLE
Can't find cssh.sh link

### ISSUE THREAD

**Issue by nvcken** [janoszen/pasztor.at#8]
Please check it https://github.com/janoszen/pasztor.at/blob/master/.cssh.sh

**Comment by janoszen** [comment]
Hello,

where was this file linked from?

Janos

**Comment by janoszen** [comment]
Closed due to missing response

**Comment by nvcken** [comment]
ON README
`.cssh.sh: Cluster SSH to all CDN nodes`

**Comment by janoszen** [comment]
Ah, thank you, since the site is no longer using a CDN that file is no longer present. You can go back in the git history to find it. I will remove it from the readme.
